version: "3.3"
services:
  frontend:
    build: frontend
    container_name: soffacto_front
    restart: unless-stopped

    ports:
      - 8085:80

    networks:
      - react-express

    depends_on:
      - backend

  backend:
    build: backend
    container_name: soffacto_backend
    restart: unless-stopped

    volumes:
      - "/home/shared/$NAME/images:/container/folder"

    env_file:
      - .env

    networks:
      - react-express
      - express-mongo

    depends_on:
      - mongo

    expose:
      - 5000

  mongo:
    container_name: soffacto_mongo
    restart: unless-stopped
    image: mongo:5.0.5
    volumes:
      - "/home/shared/$NAME/data:/data/db"
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo:
